[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "2esiwqpYjizvnSQBFcvo5cSNbgzpPVfTW2ew24YUiHj1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=38251202-3a7b-4473-be45-ea529f02b66a"
wallet  = "/Users/thc/code/solana/devnet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
