[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "2esiwqpYjizvnSQBFcvo5cSNbgzpPVfTW2ew24YUiHj1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet  = "/Users/thc/code/solana/devnet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
